### PR TITLE
fix(CMakeLists): adding necessary packages

### PR DESCRIPTION
**Pull request by iftahnaf**
Hi,

Thanks for this awesome repository!

I made some minor modifications to the `CMakeLists.txt` to include `cv_bridge` and `vision_msgs` because I encountered compilation errors when trying to build the package.

With the necessary packages added to the `CMakeLists.txt`, it now runs successfully.

### CODE REVIEW

**Comment by Ar-Ray-code** [comment]
At what stage of the build did the “compilation errors” occur?

For this project, I used `ament_cmake_auto` to write a concise CMakeList.txt that omits the packages supported by ROS. 
Thus, if the dependent packages are installed correctly, your additions should not be necessary in it.

Incidentally, the information in package.xml can be used to resolve dependencies by running the rosdep install command.

**Comment by iftahnaf** [comment]
Thanks for the comment.

When trying to build the package with `colcon build`, I had an compilation error:

`fatal error: cv_bridge/cv_bridge.hpp: No such file or directory`

I tried to install dependencies with `rosdep` before building the package:
```bash
rosdep install --from-paths src --ignore-src -r -y 
```

Eventually, in order to build the package successfully, I had to clone each dependency package and build the workspace with `colcon build`.

**Comment by Ar-Ray-code** [comment]
I don't understand your situation yet.
In what environment did you build. Are you using ros-humble?

`fatal error: cv_bridge/cv_bridge.hpp: No such file or directory` should not occur after the iron version.

**Comment by iftahnaf** [comment]
My setup is:
Pi5 8GB with Hailo HAT, Raspberry Pi OS Bookworm 64-bit.
Built ROS 2 jazzy from source with [default packages](https://raw.githubusercontent.com/ros2/ros2/jazzy/ros2.repos) as my underlay.

Then I cloned this repo, sourced the underlay and run `rosdep install --from-paths src --ignore-src -r -y `.
After this I tried to build the overlay with this package but it failed on `fatal error: cv_bridge/cv_bridge.hpp: No such file or directory`.

So I had to clone the necessary packages and change the `CMakeLists.txt` in order to build it.

**Comment by Ar-Ray-code** [comment]
Thank you for your detailed info.

Your installation procedure is correct because RaspberryPi OS cannot automatically resolve dependencies.
However, this cannot be the basis for this PR. It is probably the result of your trial and error.

You have to clone packages in [yolo_hailort.repos](https://github.com/Ar-Ray-code/rpi-bullseye-ros2/blob/jazzy/repos/yolo_hailort.repos)  beforehand before building it.  This procedure is described in my content ["RaspberryPi OSではじめるROS 2 ②"](https://zenn.dev/array/books/raspi_os_de_hajimeru_ros2_2) (but for a fee), but I omitted to explain it because this repository itself is temporary in the first place.

**Comment by iftahnaf** [comment]
OK, Thanks for the information.

I can add a readme for this repo describing how to build on Raspberry Pi OS if you want.
Was your environment under Ubuntu? If so, can I ask how you managed to solve the `libcamera` dependencies?

**Comment by Ar-Ray-code** [comment]
Requests for additional documentation are welcome. Please send us another new PullRequest. 🙇

I have tested it with RaspberryPi OS only, but it should be able to support Ubuntu + hailort_pcie_driver (Linux kernel 6.x support) which will be supported in the future.
Since the input for this node is vision_msgs::Image, it would be better to write the libcamera dependency resolution in [Ar-Ray-code/picamera_ros2](https://github.com/Ar-Ray-code/picamera_ros2).

**Pull request closed without merging**
